# game settings
#WIDTH = 270
#WIDTH = 810
#HEIGHT = 480
WIN = WIDTH, HEIGHT = 810, 480
FRAME_RATE = 60
SCROLL_SPEED = 8
GRAVITY = 1

# bat settings
BAT_POS = (WIDTH // 4, HEIGHT // 3)
BAT_SCALE = 1.5
BAT_ANIMATION_TIME = 100
BAT_JUMP_VALUE = -12
BAT_JUMP_ANGLE = 25

# ground
GROUND_HEIGHT = HEIGHT // 12
GROUND_Y = HEIGHT - GROUND_HEIGHT

# obs
OBS_WIDTH = 250
OBS_HEIGHT = HEIGHT
DIST_BETWEEN_OBS = 650
GAP_HEIGHT = 130
HALF_GAP_HEIGHT = GAP_HEIGHT // 2

#tioyj
#12:06